#pragma once

#include "driver/gpio.h"

// Waveshare ESP32-S3-Touch-LCD-7
// https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-7

#define BOARD_LCD_PIXEL_CLOCK_HZ (18 * 1000 * 1000)
#define BOARD_LCD_H_RES 800
#define BOARD_LCD_V_RES 480
#define BOARD_LCD_NUM_FB 2

#define BOARD_PIN_HSYNC GPIO_NUM_46
#define BOARD_PIN_VSYNC GPIO_NUM_3
#define BOARD_PIN_DE GPIO_NUM_5
#define BOARD_PIN_PCLK GPIO_NUM_7
#define BOARD_PIN_DISP_EN GPIO_NUM_NC

#define BOARD_PIN_DATA0 GPIO_NUM_14
#define BOARD_PIN_DATA1 GPIO_NUM_38
#define BOARD_PIN_DATA2 GPIO_NUM_18
#define BOARD_PIN_DATA3 GPIO_NUM_17
#define BOARD_PIN_DATA4 GPIO_NUM_10
#define BOARD_PIN_DATA5 GPIO_NUM_39
#define BOARD_PIN_DATA6 GPIO_NUM_0
#define BOARD_PIN_DATA7 GPIO_NUM_45
#define BOARD_PIN_DATA8 GPIO_NUM_48
#define BOARD_PIN_DATA9 GPIO_NUM_47
#define BOARD_PIN_DATA10 GPIO_NUM_21
#define BOARD_PIN_DATA11 GPIO_NUM_1
#define BOARD_PIN_DATA12 GPIO_NUM_2
#define BOARD_PIN_DATA13 GPIO_NUM_42
#define BOARD_PIN_DATA14 GPIO_NUM_41
#define BOARD_PIN_DATA15 GPIO_NUM_40

#define BOARD_I2C_SDA GPIO_NUM_8
#define BOARD_I2C_SCL GPIO_NUM_9
#define BOARD_I2C_PORT 0
#define BOARD_I2C_FREQ_HZ 400000
#define BOARD_I2C_TIMEOUT_MS 1000

#define BOARD_PIN_TOUCH_RST GPIO_NUM_4

#define BOARD_PIN_CAN_RX GPIO_NUM_19
#define BOARD_PIN_CAN_TX GPIO_NUM_20

/* Bande WS2812, même broche que Dash-S-bastien. */
#define BOARD_PIN_LED_STRIP GPIO_NUM_6
#define BOARD_LED_COUNT 16
#define BOARD_CAN_BITRATE 1000000
#define BOARD_CAN_TASK_STACK 4096
#define BOARD_CAN_TASK_PRIORITY 1

#define BOARD_IO_EXPANDER_ADDR 0x24
#define BOARD_TOUCH_RESET_ADDR 0x38

#define BOARD_LVGL_TICK_PERIOD_MS 2
#define BOARD_LVGL_TASK_STACK 8192
#define BOARD_LVGL_TASK_PRIORITY 2
/* ~50 Hz UI/LEDs: smoother than 40 ms without flooding FULL-mode PSRAM flushes. */
#define BOARD_UI_PERIOD_MS 20
